### ISSUE TITLE
Does drama utilize only one CPU core?

### ISSUE THREAD

**Issue by paulmillr** [stagas/drama#1]
@stagas? Or it does some parallelism magic?

**Comment by stagas** [comment]
No. You can create forked systems (which use child processes) that will occupy the remaining free cores. A single actor system is single core, if that's what you're asking:

``` javascript
var sys = drama('sys'); // a system in this process named 'sys'
var forked = sys.fork('forked'); // creates a system in a child process
```

The API for local and remote systems is the same. I'll create documentation for these as soon as I find time. In the meanwhile take a look at the examples, all of the features are utilized there. Here's an example of distributed PI calculation that uses multiple processes/threads/systems https://github.com/stagas/drama/blob/master/examples/distributed-pi.js#L44

**Comment by paulmillr** [comment]
what so you think about making drama auto-use all cores? shouldnt be hard, examining examples. it will make it like erlang.

**Comment by stagas** [comment]
Interesting. And what would be the distribution strategy? Now you have the freedom to create your own scaling strategy, and introduce more system interfaces than just extra processes/cores, like a web browser or through a TCP socket.

**Comment by stagas** [comment]
To introduce a new interface, use `sys.fork(address, bus)` where `bus` is the interface bus you like to use. The bus is just an interface with a `.send()` and an `.on('message', fn)`. On the other side, you just pass the parent bus in your main system like this: `var sys = drama(setup.address, parent)`. The `setup` object is the first thing the parent system sends to the child. See https://github.com/stagas/drama/blob/master/examples/websocket-client.js

Bah, I should write docs.

**Comment by paulmillr** [comment]
I know, freedom is great, but automatic SMP is even awesomier. The whole point of erlang stuff is that devs don't need to care about how many cores their system have, they can load it all.

No ideas about distr strategy.
